// This file is auto-generated by scripts/update-edge-file.js
// Do not edit manually - changes will be overwritten
// Generated at: PLACEHOLDER_TIMESTAMP

/**
 * Edge function to apply redirects and rewrites
 * Rules are fetched from Contentstack and injected at build/update time
 */
export default async function middleware(req, context) {
  const url = new URL(req.url);
  const pathname = url.pathname;

  // Dynamic rules (injected by script)
  // PLACEHOLDER_RULES

  // Apply redirects and rewrites
  for (const rule of rules) {
    const isMatch =
      pathname === rule.from ||
      pathname.startsWith(rule.from + "/") ||
      matchPattern(pathname, rule.from);

    if (isMatch) {
      if (rule.type === "redirect") {
        const destination = rule.to.startsWith("http")
          ? rule.to
          : `${url.origin}${rule.to}`;

        const statusCode = rule.statusCode || (rule.permanent ? 301 : 307);

        return new Response(null, {
          status: statusCode,
          headers: {
            Location: destination,
          },
        });
      } else if (rule.type === "rewrite") {
        const destination = rule.to.startsWith("http")
          ? rule.to
          : `${url.origin}${rule.to}`;

        // For rewrite, fetch the destination and return it
        const response = await fetch(destination, {
          method: req.method,
          headers: req.headers,
          body: req.body,
        });

        return response;
      }
    }
  }

  // No match found, continue with normal request
  return context.next();
}

// Simple pattern matching (supports * wildcard)
function matchPattern(pathname, pattern) {
  if (!pattern.includes("*")) {
    return pathname === pattern;
  }

  // Convert pattern to regex
  const regexPattern = pattern.replace(/\*/g, ".*").replace(/\//g, "\\/");

  const regex = new RegExp(`^${regexPattern}$`);
  return regex.test(pathname);
}
